#!/bin/bash

# Word list for attacks
wl=""
# List of created hashes for attack
hash_list=()

good_hash=0

bad_hash=0

# Function for converting pcap to h22000
conv_hccap () {
	local pcap=$1
	hccap_name=$(basename "$pcap" .${pcap##*.})".hc22000"

	hcxpcapngtool -o $HOME/gotchi/hash/$hccap_name $pcap | grep "RC checked" > /dev/null 2>&1

	hc_check=$?
	if [ $hc_check -eq 0 ]; then
		echo "[SUCCESS]........: $hccap_name"
		hash_list+=("$hccap_name")
		let "good_hash++"
		sleep 0.5
	else
		let "bad_hash++"
		echo "[FAILED].........: $hccap_name"
	fi
}

# Function for running hashcat
hash_crack () {
	if [[ "${#hash_list[@]}" -gt 1 ]]; then
		echo ""
		echo Created..........:"$good_hash"
		echo Failed...........:"$bad_hash"
		echo ""
	else	
		echo ""
	fi
	for hash in "${hash_list[@]}"; do
		echo Target...........:$hash
		hashcat -m 22000 $HOME/gotchi/hash/$hash $wl --status --status-timer=2 2>&1 | grep --line-buffered -E "Progress" | awk '{printf "\r%s", $0}'
		echo ""
		echo ""
	done
}

# Function for directory based attacks
dir_atk_fun () {
        local atk_dir=$1
        if [[ -d $atk_dir ]]; then
                for file in $atk_dir/*; do
                	if [[ "${file##*.}" == "pcap" || "${file##*.}" == "pcapng" ]]; then
						conv_hccap "$file"
                    else
                        echo "[FILE FORMAT INVALID]...""$file"
                    fi
                done

		if [[ ${#hash_list[@]} -eq 0 ]]; then
                	echo "[NO HASHES CREATED]"
                        	exit 0
                	else
                                hash_crack
               	fi
        else
                echo "[DIRECTORY NOT FOUND]"
        fi
}

# Function for single file based attacks
file_atk_fun () {
	local atk_file=$1
	if [[ -f "$atk_file" && "${atk_file##*.}" == "pcap" ]]; then
        	conv_hccap "$atk_file"
	else
        	echo "[PCAP FILE NOT FOUND]"
	fi

	if [[ ${#hash_list[@]} -eq 0 ]]; then
                echo "[NO HASHES CREATED]"
                exit 1
        else
                hash_crack
        fi

}

while getopts "f:d:l:h" opt; do
	case $opt in
		f)
			file_atk_fun "$OPTARG"
		;;
		d)
			dir_atk_fun "$OPTARG"
		;;
		l)
			if [[ -f $OPTARG && "${OPTARG##*.}" == "txt" ]]; then
				wl="$OPTARG"
			else
				echo "[WORD LIST NOT FOUND. FORMAT MUST BE .txt]"
				exit 0
			fi
		;;
		h)
			#	Print help screen
			echo
			echo "Basic use: gotchi -l <wordlist(full path)>  [ -option <arg full path]>] "
			echo
			echo "OPTIONS:  "
			echo "pwnit -l <wordlist (required)>		 Specify word list for attack. Switch is required to run and" 
			echo "						 following switches. (use full path)"
			echo
			echo "pwnit <wl> -f <pcap file(full path)>	 Used for individual capture attack. Must be .pcap or .pcapng"
			echo
			echo "pwnit <wl> -d <directory(full path)>	 Used for attack on directories full of capture files. Will flag"
			echo "					if conversion failes. If more than one file succesfully converted"
		;;
	esac
done 
